// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7dkz97fsO5aOHifz84Vs7AhVC5KjJhNo',
    appId: '1:754574871779:web:efccb97aefa98b986309d6',
    messagingSenderId: '754574871779',
    projectId: 'otakuoasis-4f0bb',
    authDomain: 'otakuoasis-4f0bb.firebaseapp.com',
    storageBucket: 'otakuoasis-4f0bb.appspot.com',
    measurementId: 'G-R91PD5CYSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWneEW8YCZG_07EfN-pBYvI3Z1aCTUSc',
    appId: '1:754574871779:android:fe5a2185590bd2256309d6',
    messagingSenderId: '754574871779',
    projectId: 'otakuoasis-4f0bb',
    storageBucket: 'otakuoasis-4f0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7ayuX8ZCDOIC0t1_aF-u8ui8Lz_0uLc',
    appId: '1:754574871779:ios:392e6b0b5f15c3596309d6',
    messagingSenderId: '754574871779',
    projectId: 'otakuoasis-4f0bb',
    storageBucket: 'otakuoasis-4f0bb.appspot.com',
    iosBundleId: 'com.example.animeWorldTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW7ayuX8ZCDOIC0t1_aF-u8ui8Lz_0uLc',
    appId: '1:754574871779:ios:392e6b0b5f15c3596309d6',
    messagingSenderId: '754574871779',
    projectId: 'otakuoasis-4f0bb',
    storageBucket: 'otakuoasis-4f0bb.appspot.com',
    iosBundleId: 'com.example.animeWorldTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7dkz97fsO5aOHifz84Vs7AhVC5KjJhNo',
    appId: '1:754574871779:web:eea2ab9b40bd215b6309d6',
    messagingSenderId: '754574871779',
    projectId: 'otakuoasis-4f0bb',
    authDomain: 'otakuoasis-4f0bb.firebaseapp.com',
    storageBucket: 'otakuoasis-4f0bb.appspot.com',
    measurementId: 'G-SXX99V1703',
  );

}